version: '3.8'

services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: 'ccms-postgres'
    restart: 'always'
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
  redis:
    image: 'redis:6-alpine'
    container_name: 'ccms-redis'
    command: 'redis-server --requirepass password'
    restart: 'always'
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'

volumes:
  postgres-data:
  redis-data:
