import { Command } from 'commander';

import { runCommand } from '../utils';

function action() {
  runCommand('pnpm run clean --recursive && rm -rf node_modules');
}

export const cleanCommand = (program: Command) => {
  program.command('clean').description('Removes all artifacts generated by build tools.').action(action);
};
