const { spawnSync } = require('child_process');

async function action() {
  const command = `turbo run clean && rm -rf node_modules`;

  spawnSync(command, { stdio: 'inherit', shell: true, encoding: 'utf-8' });
}

module.exports = (program) => {
  program.command('clean').description('Removes all artifacts generated by build tools').action(action);
};
