const { runCommand } = require('../utils');

async function action() {
  runCommand('pnpm run clean --recursive && rm -rf node_modules');
}

module.exports = (program) => {
  program.command('clean').description('Removes all artifacts generated by build tools.').action(action);
};
