import { Argument, Command } from 'commander';

import { workspacesUtils } from '@ccms/node';

import { loadEnvVariables, runCommand } from '../utils';

interface Arguments {
  workspaces: string[];
}

function action(workspaces: Arguments['workspaces']) {
  loadEnvVariables();

  if (workspaces.length === 0) {
    runCommand('pnpm run generate --recursive');

    return;
  }

  const filters = workspacesUtils
    .findManyOrThrow(workspaces)
    .map((workspace) => `--filter=${workspace.moduleName}`)
    .join(' ');

  runCommand(`pnpm run generate ${filters}`);
}

export const generateCommand = (program: Command) => {
  program
    .command('generate')
    .description('Creates autogenerated files in provided workspaces.')
    .addArgument(
      new Argument(
        '[workspaces...]',
        'Names of the workspaces to run the generate command. Leave empty to generate for all dependencies.'
      ).choices(workspacesUtils.getDirectoryNames())
    )
    .action(action);
};
