name: Code Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.2
          run_install: true

      - name: Run ESLint on changed files
        run: pnpm lint:changed
